Repository eclipse-ee4j/yasson, pull requests merged in 2018-12, with the labels that each got.

#179 Change org.glassfish:javax.json to optional compile dependency
  pom.xml
Labels: enhancement

#200 Check that property is writable before attempting to deserialize
  src/main/java/org/eclipse/yasson/internal/serializer/ObjectDeserializer.java
  src/test/java/org/eclipse/yasson/defaultmapping/basic/PropertyMismatchTest.java
Labels: bug

#198 Temporarily enable staging repository by default
  pom.xml
Labels: build

#202 Fix for JsonbCreator with parameterized type.
  src/main/java/org/eclipse/yasson/internal/model/CreatorModel.java
  src/test/java/org/eclipse/yasson/customization/JsonbCreatorTest.java
Labels: bug
