Repository eclipse-ee4j/yasson, pull requests merged in 2019-11, with the labels that each got.

#358 Add github issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other-issue.md
Labels: housekeeping

#357 Fix issue where equivalent properties are not merged correctly
  src/main/java/org/eclipse/yasson/internal/ClassParser.java
  src/main/java/org/eclipse/yasson/internal/Marshaller.java
  src/main/java/org/eclipse/yasson/internal/Unmarshaller.java
  src/main/java/org/eclipse/yasson/internal/model/ClassModel.java
  src/main/java/org/eclipse/yasson/internal/model/PropertyModel.java
  src/main/java/org/eclipse/yasson/internal/serializer/AbstractArrayDeserializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/AbstractContainerSerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/AdaptedObjectSerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/ContainerDeserializerUtils.java
  src/test/java/org/eclipse/yasson/customization/JsonbPropertyTest.java
Labels: bug

#344 Replace inner interface inside ComponentMatcher
  src/main/java/org/eclipse/yasson/internal/ComponentMatcher.java
Labels: housekeeping

#334 Refactor JsonbAnnotatedElement.java, remove JsonbAnnotated.java
  src/main/java/org/eclipse/yasson/internal/model/JsonbAnnotated.java
  src/main/java/org/eclipse/yasson/internal/model/JsonbAnnotatedElement.java
Labels: housekeeping

#362 Support for GraalVM native-image.
  src/main/resources/META-INF/native-image/native-image.properties
Labels: enhancement

#359 StackOverflowError on recursive references
  src/main/java/org/eclipse/yasson/internal/model/JsonbAnnotated.java
  src/main/java/org/eclipse/yasson/internal/serializer/ObjectSerializer.java
  src/main/resources/META-INF/native-image/native-image.properties
  src/test/java/org/eclipse/yasson/adapters/model/Chain.java
  src/test/java/org/eclipse/yasson/adapters/model/ChainAdapter.java
  src/test/java/org/eclipse/yasson/adapters/model/ChainSerializer.java
  src/test/java/org/eclipse/yasson/adapters/model/Foo.java
  src/test/java/org/eclipse/yasson/adapters/model/FooAdapter.java
  src/test/java/org/eclipse/yasson/adapters/model/FooSerializer.java
  src/test/java/org/eclipse/yasson/defaultmapping/specific/RecursiveReferenceTest.java
Labels: bug

#364 Do not log WARN message when optional generic bound is not found
  src/main/java/org/eclipse/yasson/internal/ComponentMatcher.java
  src/main/java/org/eclipse/yasson/internal/ReflectionUtils.java
Labels: bug
