Repository eclipse-ee4j/yasson, pull requests merged in 2019-10, with the labels that each got.

#315 New map serializer/deserializer
  src/main/java/org/eclipse/yasson/internal/serializer/AbstractArraySerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/AbstractContainerDeserializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/AbstractContainerSerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/ByteArraySerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/CollectionSerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/ContainerDeserializerUtils.java
  src/main/java/org/eclipse/yasson/internal/serializer/DeserializerBuilder.java
  src/main/java/org/eclipse/yasson/internal/serializer/DoubleArraySerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/FloatArraySerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/IntArraySerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/JsonArraySerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/JsonObjectSerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/LongArraySerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/MapEntriesArrayDeserializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/MapSerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/MapToEntriesArraySerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/MapToObjectSerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/ObjectArraySerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/ObjectSerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/SerializerBuilder.java
  src/main/java/org/eclipse/yasson/internal/serializer/ShortArraySerializer.java
  src/test/java/org/eclipse/yasson/serializers/MapToEntriesArraySerializerTest.java
  src/test/java/org/eclipse/yasson/serializers/SerializersTest.java
  src/test/java/org/eclipse/yasson/serializers/model/Pokemon.java
  src/test/java/org/eclipse/yasson/serializers/model/Trainer.java
Labels: enhancement

#347 FIX/345 : Serializing enums in maps keys issue
  src/main/java/org/eclipse/yasson/internal/serializer/MapToObjectSerializer.java
  src/test/java/org/eclipse/yasson/serializers/MapToObjectSerializerTest.java
Labels: bug

#349 Fix compile errors in MapToObjectSerializerTest due to soft merge conflict
  src/test/java/org/eclipse/yasson/customization/PropertyOrderTest.java
  src/test/java/org/eclipse/yasson/serializers/MapToObjectSerializerTest.java
Labels: bug, build

#338 Update to Jakarta dependencies
  README.md
  pom.xml
Labels: housekeeping
