Repository eclipse-ee4j/yasson, pull requests merged in 2020-04, with the labels that each got.

#396 Backport recent bug fixes to 1.0.X
  src/main/java/org/eclipse/yasson/internal/AnnotationIntrospector.java
  src/main/java/org/eclipse/yasson/internal/MappingContext.java
  src/main/java/org/eclipse/yasson/internal/Marshaller.java
  src/main/java/org/eclipse/yasson/internal/ReflectionUtils.java
  src/main/java/org/eclipse/yasson/internal/Unmarshaller.java
  src/main/java/org/eclipse/yasson/internal/serializer/BooleanArrayDeserializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/BooleanArraySerializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/DeserializerBuilder.java
  src/main/java/org/eclipse/yasson/internal/serializer/SerializerBuilder.java
  src/test/java/org/eclipse/yasson/adapters/AdaptersTest.java
  src/test/java/org/eclipse/yasson/defaultmapping/basic/BooleanTest.java
Labels: backport

#402 Update copyright years to fix CI builds
  src/main/java/org/eclipse/yasson/internal/AnnotationIntrospector.java
  src/main/java/org/eclipse/yasson/internal/MappingContext.java
  src/main/java/org/eclipse/yasson/internal/ReflectionUtils.java
  src/main/java/org/eclipse/yasson/internal/Unmarshaller.java
  src/main/java/org/eclipse/yasson/internal/serializer/DeserializerBuilder.java
  src/main/java/org/eclipse/yasson/internal/serializer/SerializerBuilder.java
  src/test/java/org/eclipse/yasson/adapters/AdaptersTest.java
  src/test/java/org/eclipse/yasson/defaultmapping/basic/BooleanTest.java
Labels: housekeeping

#401 Don't use reflection when possible
  src/main/java/org/eclipse/yasson/internal/model/ClassModel.java
Labels: enhancement

#403 Don't use reflection when possible
  src/main/java/org/eclipse/yasson/internal/model/ClassModel.java
Labels: enhancement
