Repository eclipse-ee4j/yasson, pull requests merged in 2020-07, with the labels that each got.

#436 Add support for serializing and deserializing java.nio.path
  src/main/java/org/eclipse/yasson/internal/serializer/DefaultSerializers.java
  src/main/java/org/eclipse/yasson/internal/serializer/PathTypeDeserializer.java
  src/main/java/org/eclipse/yasson/internal/serializer/PathTypeSerializer.java
  src/test/java/org/eclipse/yasson/defaultmapping/typeConvertors/DefaultSerializersTest.java
Labels: enhancement

#416 Update CI to run TCK properly
  .travis.yml
  src/main/java/org/eclipse/yasson/internal/serializer/ZoneIdTypeSerializer.java
  src/test/java/org/eclipse/yasson/defaultmapping/dates/DatesTest.java
  yasson-tck/pom.xml
Labels: bug

#438 Switch to using MethodHandles for property value propagations
  src/main/java/org/eclipse/yasson/internal/ClassParser.java
  src/main/java/org/eclipse/yasson/internal/model/GetValueCommand.java
  src/main/java/org/eclipse/yasson/internal/model/MethodHandleValuePropagation.java
  src/main/java/org/eclipse/yasson/internal/model/PropertyModel.java
  src/main/java/org/eclipse/yasson/internal/model/PropertyValuePropagation.java
  src/main/java/org/eclipse/yasson/internal/model/ReflectionPropagation.java
  src/main/java/org/eclipse/yasson/internal/model/SetValueCommand.java
  src/test/java/org/eclipse/yasson/DefaultGetterInInterface.java
  src/test/java/org/eclipse/yasson/defaultmapping/modifiers/ClassModifiersTest.java
Labels: enhancement

#440 Fix Issue #435
  pom.xml
  src/test/java/org/eclipse/yasson/customization/PrettyPrintTest.java
  src/test/java/org/eclipse/yasson/documented/DocumentationExampleTest.java
Labels: housekeeping
